const fs = require('node:fs');
const path = require('node:path');

// Explicit publication boundary. Vercel packages api/ and their server imports
// separately; neither backend source nor repository metadata belongs on the CDN.
const publicFiles = [
  'index.html', 'account.html', 'admin.html', 'support.html', 'success.html',
  'privacy.html', 'terms.html', 'refunds.html', 'legal.html', '404.html',
  'account.js', 'admin.js', 'support.js', 'success.js', 'home-demo.js',
  'navigation.js', 'downloads.js', 'checkout.js', 'cookie-banner.js',
  'home.css', 'quiet-theme.css', 'account.css', 'account-additions.css',
  'admin.css', 'support.css', 'legal.css', 'cookie-banner.css',
  'manifest.webmanifest', 'robots.txt', 'sitemap.xml',
  ...['zap-icon-512.png', 'zap-og-card.png', 'zap-favicon.svg', 'zap-icon-192.png', 'zap-icon.svg', 'apple-touch-icon.png'].map((name) => `brand/zap/${name}`),
];
function build(output = path.join(__dirname, 'public')) {
  // This directory is generated by this build and is excluded from version control.
  fs.rmSync(output, { recursive: true, force: true });
  fs.mkdirSync(output, { recursive: true });
  for (const file of publicFiles) {
    const source = path.join(__dirname, file);
    if (!fs.lstatSync(source).isFile()) throw new Error(`Invalid public asset: ${file}`);
    const target = path.join(output, file);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.copyFileSync(source, target);
  }
  console.log(`Published ${publicFiles.length} approved static assets. Backend source excluded.`);
}
if (require.main === module) build();
module.exports = { build, publicFiles };
