const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('dripType', Object.freeze({
  start: (text) => ipcRenderer.invoke('drip-type:start', text),
  cancel: () => ipcRenderer.send('drip-type:cancel'),
  showQuick: () => ipcRenderer.send('quick:show'),
  closeQuick: () => ipcRenderer.send('quick:close'),
  readClipboardText: () => ipcRenderer.invoke('clipboard:read-text'),
  writeClipboardText: (value) => ipcRenderer.invoke('clipboard:write-text', value),
  listTemplates: () => ipcRenderer.invoke('templates:list'),
  saveTemplate: (template) => ipcRenderer.invoke('templates:save', template),
  deleteTemplate: (id) => ipcRenderer.invoke('templates:delete', id),
  installTemplateLibrary: () => ipcRenderer.invoke('templates:install-library'),
  listProfiles: () => ipcRenderer.invoke('profiles:list'),
  saveProfile: (profile) => ipcRenderer.invoke('profiles:save', profile),
  activateProfile: (id) => ipcRenderer.invoke('profiles:activate', id),
  deleteProfile: (id) => ipcRenderer.invoke('profiles:delete', id),
  listClipboardItems: (query) => ipcRenderer.invoke('clipboard-workspace:list', query),
  captureClipboardItem: () => ipcRenderer.invoke('clipboard-workspace:capture'),
  updateClipboardItem: (id, action) => ipcRenderer.invoke('clipboard-workspace:update', id, action),
  renderBatch: (body, input) => ipcRenderer.invoke('pro:batch-render', body, input),
  transformWriting: (value, mode) => ipcRenderer.invoke('pro:transform', value, mode),
  showMain: () => ipcRenderer.send('main:show'),
  replayOnboarding: () => ipcRenderer.send('onboarding:replay'),
  completeOnboarding: (settings) => ipcRenderer.invoke('onboarding:complete', settings),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (settings) => ipcRenderer.invoke('settings:save', settings),
  getAccessibility: () => ipcRenderer.invoke('accessibility:get'),
  requestAccessibility: () => ipcRenderer.invoke('accessibility:request'),
  getPermissionChecklist: () => ipcRenderer.invoke('permissions:get'),
  requestAutomation: () => ipcRenderer.invoke('automation:request'),
  getAppInfo: () => ipcRenderer.invoke('app:get-info'),
  getBillingState: () => ipcRenderer.invoke('billing:get-state'),
  refreshBilling: () => ipcRenderer.invoke('billing:refresh'),
  subscribe: () => ipcRenderer.invoke('billing:subscribe'),
  manageBilling: () => ipcRenderer.invoke('billing:portal'),
  getUpdateState: () => ipcRenderer.invoke('updater:get-state'),
  checkForUpdates: () => ipcRenderer.invoke('updater:check'),
  downloadUpdate: () => ipcRenderer.invoke('updater:download'),
  installUpdate: () => ipcRenderer.send('updater:install'),
  onState: (callback) => ipcRenderer.on('drip-type:state', (_event, state) => callback(state)),
  onQuickOpened: (callback) => ipcRenderer.on('quick:opened', (_event, data) => callback(data)),
  onTheme: (callback) => ipcRenderer.on('theme:changed', (_event, data) => callback(data)),
  onUpdate: (callback) => ipcRenderer.on('updater:state', (_event, state) => callback(state)),
  onBilling: (callback) => ipcRenderer.on('billing:state', (_event, state) => callback(state)),
  onNavigate: (callback) => ipcRenderer.on('app:navigate', (_event, target) => callback(target))
}));
