const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('dripType', Object.freeze({
  getZapStatus: () => ipcRenderer.invoke('zap:status'),
  saveZapSettings: (settings) => ipcRenderer.invoke('zap:settings', settings),
  requestZap: (request) => ipcRenderer.invoke('zap:request', request),
  cancelZap: () => ipcRenderer.send('zap:cancel'),
  getZapDisplays: () => ipcRenderer.invoke('zap:displays'),
  captureZapScreen: (displayId) => ipcRenderer.invoke('zap:capture', displayId),
  openZapScreenSettings: () => ipcRenderer.invoke('zap:screen-settings'),
  openZapSource: (url) => ipcRenderer.invoke('zap:open-source', url),
  pinZapAnswer: (text) => ipcRenderer.invoke('zap:pin', text),
  getZapPin: () => ipcRenderer.invoke('zap:pin-text'),
  closeZapPin: () => ipcRenderer.send('zap:pin-close'),
  onZapPin: (callback) => ipcRenderer.on('zap:pin-changed', (_event, text) => callback(text)),
  getAppearance: () => ipcRenderer.invoke('appearance:get'),
  start: (text) => ipcRenderer.invoke('drip-type:start', text),
  cancel: () => ipcRenderer.send('drip-type:cancel'),
  showQuick: () => ipcRenderer.send('quick:show'),
  closeQuick: () => ipcRenderer.send('quick:close'),
  toggleQuickFullScreen: () => ipcRenderer.invoke('quick:toggle-full-screen'),
  readClipboardText: () => ipcRenderer.invoke('clipboard:read-text'),
  writeClipboardText: (value) => ipcRenderer.invoke('clipboard:write-text', value),
  showMain: () => ipcRenderer.send('main:show'),
  replayOnboarding: () => ipcRenderer.send('onboarding:replay'),
  completeOnboarding: (settings) => ipcRenderer.invoke('onboarding:complete', settings),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (settings) => ipcRenderer.invoke('settings:save', settings),
  getAccessibility: () => ipcRenderer.invoke('accessibility:get'),
  requestAccessibility: () => ipcRenderer.invoke('accessibility:request'),
  getPermissionChecklist: () => ipcRenderer.invoke('permissions:get'),
  requestAutomation: () => ipcRenderer.invoke('automation:request'),
  getAppInfo: () => ipcRenderer.invoke('app:get-info'),
  getBillingState: () => ipcRenderer.invoke('billing:get-state'),
  refreshBilling: () => ipcRenderer.invoke('billing:refresh'),
  subscribe: () => ipcRenderer.invoke('billing:subscribe'),
  signIn: () => ipcRenderer.invoke('account:sign-in'),
  signOut: () => ipcRenderer.invoke('account:sign-out'),
  openAccount: () => ipcRenderer.invoke('account:open'),
  onSignedOut: (callback) => ipcRenderer.on('account:signed-out', () => callback()),
  manageBilling: () => ipcRenderer.invoke('billing:portal'),
  getUpdateState: () => ipcRenderer.invoke('updater:get-state'),
  checkForUpdates: () => ipcRenderer.invoke('updater:check'),
  downloadUpdate: () => ipcRenderer.invoke('updater:download'),
  installUpdate: () => ipcRenderer.send('updater:install'),
  onState: (callback) => ipcRenderer.on('drip-type:state', (_event, state) => callback(state)),
  onQuickOpened: (callback) => ipcRenderer.on('quick:opened', (_event, data) => callback(data)),
  onQuickFullScreen: (callback) => ipcRenderer.on('quick:full-screen-changed', (_event, value) => callback(Boolean(value))),
  onTheme: (callback) => ipcRenderer.on('theme:changed', (_event, data) => callback(data)),
  onUpdate: (callback) => ipcRenderer.on('updater:state', (_event, state) => callback(state)),
  onBilling: (callback) => ipcRenderer.on('billing:state', (_event, state) => callback(state)),
  onNavigate: (callback) => ipcRenderer.on('app:navigate', (_event, target) => callback(target))
}));
